baseURL = "https://msio.me"
languageCode = "en-us"
title = "PORTFOLIO SITE"

[params]
    defaultTitle = false

    FirstName = 'Muhammed A.'
    LastName = 'Senghore'
    skills = ['Linux', 'Git', 'Cybersecurity', 'Basic Electronics', 'Basic C & Python', 'Basic HTML, CSS, & JS']
    SiteDescription = 'A showcase of my skills & work, including projects in C, Python & Cybersecurity'

    JobTitle = "Student"
    Organization = "Freelance / Self-employed"

    Education = "S.O.S Hermann Gmeiner Technical Senior Secondary School"
    Institution = "High School Diploma"

[params.Profile]
    Greetings = "Howdy!"
    summary = [
        'I’m Muhammed, & I’m a student living in Istanbul, Turkey. I’m a tech enthusiast with a knack for cybersecurity.',
        'I love solving challenges on platforms like [TryHackMe](https://tryhackme.com/p/msio/), building up my skills, and staying on top of the latest industry trends.',
        'I graduated with a High School diploma from S.O.S Hermann Gmeiner Technical Senior Secondary School in 2018.'
    ]
    Email = "nbytes808@gmail.com"

[params.rssFeed]
    Url = "https://blog.msio.me/feed.xml"

[params.Socials]
    GitHub = "https://github.com/msio808"
    LinkedIn = "https://linkedin.com/in/msio808"
    Instagram = "https://instagram.com/msio808"
    BlueSky = "https://bsky.app/profile/msio.me"
    YouTube = "https://youtube.com/@synercodex"
    HackerRank = "https://hackerrank.com/profile/mrmasio/"

[params.Footer]
    ccName = "Muhammed A"
    ccEmail = nbytes808@gmail.com

[params.analytics]
    GoatCounter = 'G-CL14LX3KFN'
    GoogleAnaltics = 'msio'



# Do not edit
[outputs]
    home = ["HTML", "RSS"]
[minify]
    minifyOutput = true
enableRobotsTXT = true
enableFingerprinting = true
[taxonomies]
